repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
      - id: gitleaks-docker
  - repo: https://github.com/python-poetry/poetry
    rev: '2.1.3'  # add version here
    hooks:
    -   id: poetry-check
      #-   id: poetry-lock
      #-   id: poetry-export
  #- repo: https://github.com/psf/black
  #  rev: '25.1.0'
  #  hooks:
  #    - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v6.0.0'
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  #- repo: https://github.com/PyCQA/flake8
  #  rev: '7.3.0'
  #  hooks:
  #    - id: flake8
